### ISSUE TITLE
No module named twisted.internet.defer

### ISSUE THREAD

**Issue by and7ey** [ggaughan/testpipe#1]
Looks like the documentation is not full, I've uploaded everything to GAE as is and get the following error:

```
<type 'exceptions.ImportError'>: No module named twisted.internet.defer
Traceback (most recent call last):
  File "/base/data/home/apps/s~myappid/1.385409930530696167/main.py", line 20, in <module>
    from pipe_UuvYtuMe3hGDsmRgPm7D0g import pipe_UuvYtuMe3hGDsmRgPm7D0g
  File "/base/data/home/apps/s~myappid/1.385409930530696167/pipe_UuvYtuMe3hGDsmRgPm7D0g.py", line 4, in <module>
    from pipe2py.modules import *
  File "/base/data/home/apps/s~myappid/1.385409930530696167/pipe2py/modules/__init__.py", line 9, in <module>
    from twisted.internet.defer import maybeDeferred, inlineCallbacks, returnValue
```

(and, believe, the code should be updated to Python 2.7, 2.5 is depreciated).

**Comment by ggaughan** [comment]
You may have better luck with the pre-twisted (etc.) version: 
https://github.com/ggaughan/pipe2py/tree/6a5c31eb218904a17800387bc4cd4239ba1b0b34

**Comment by and7ey** [comment]
Thanks, that version works well with GAE.

Could you please make an online tool to convert json files downloaded to py files (and looks like no pipes are working at http://pipes-engine.appspot.com/)? Due to multiple dependencies I can not get `compile.py` running properly locally.
